---
sidebar: sidebar 
permalink: task-set-up-gcnv.html 
keywords: setup, set up, api, service account, requirements, permissions, google cloud netapp volumes, gcnv, bluexp, netapp console 
summary: La NetApp Console necesita acceso a la API de Google Cloud NetApp Volumes y los permisos adecuados a través de una cuenta de servicio de Google Cloud. 
---
= Configurar Google Cloud NetApp Volumes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La NetApp Console necesita los permisos adecuados a través de una cuenta de servicio de Google Cloud.

Completa las siguientes tareas para que NetApp Console pueda acceder a tu proyecto de Google Cloud.


NOTE: Puedes utilizar la consola de Google Cloud o la CLI de gcloud para estas tareas. Para utilizar la CLI de gcloud, debes tener link:https://cloud.google.com/sdk/docs/install-sdk["instalaste la CLI de Google Cloud"^] primero.

* Si aún no tiene una cuenta de servicio existente, cree una nueva.
* Conceder acceso para suplantación de identidad.
* Otorgar el rol de IAM en el proyecto compartido.




[[set-up-a-service-account]]
== Configurar una cuenta de servicio


NOTE: Los cambios en los permisos de los proyectos de Google Cloud pueden tardar un par de minutos en surtir efecto.

. En la consola de Google Cloud, https://console.cloud.google.com/iam-admin/serviceaccounts["Vaya a la página de Cuentas de servicio"^] .
. Haga clic en *Seleccionar un proyecto*, elija su proyecto y haga clic en *Abrir*.
. Para crear una cuenta de servicio, haga lo siguiente:
+
.. Haga clic en *Crear cuenta de servicio*.
.. Ingrese el nombre de la cuenta de servicio (nombre para mostrar descriptivo) y la descripción.
+
Google Cloud Console genera un ID de cuenta de servicio basado en este nombre.  Edite la ID si es necesario: no podrá cambiarla más tarde.

.. Haga clic en *Crear y continuar*.
.. En la lista de roles, selecciona el rol *Google Cloud NetApp Volumes Admin* o *Google Cloud NetApp Volumes Viewer*.
.. Seleccione *Continuar*.
+
Alternativamente, puedes asignar el rol usando la CLI de gcloud:

+
[source, cli]
----
gcloud projects add-iam-policy-binding <YOUR_PROJECT_ID> --member="serviceAccount:<YOUR_SA_EMAIL>" --role="roles/netapp.admin"
----
.. Otorgar acceso de suplantación a esta cuenta de servicio: credentials-sa@wf-production-netapp.iam.gserviceaccount.com. Para más detalles, consulte https://cloud.google.com/iam/docs/create-short-lived-credentials-direct#sa-credentials-jwt["Crear un token web JSON autofirmado (JWT)"^] .
+
La cuenta de servicio propiedad de NetApp se utiliza para solicitar un token de acceso de corta duración que le permite actuar como esa cuenta de servicio sin necesidad de acceder a su clave privada.

+
Alternativamente, puedes conceder acceso de suplantación utilizando la CLI de gcloud:

+
[source, cli]
----
gcloud iam service-accounts add-iam-policy-binding <YOUR_SA_EMAIL> --member="serviceAccount:credentials-sa@wf-production-netapp.iam.gserviceaccount.com" --role="roles/iam.serviceAccountTokenCreator" --project=<YOUR_PROJECT_ID>
----
.. Haga clic en *HECHO* en la parte inferior de la página y continúe con el siguiente paso.






[[shared-vpc]]
== VPC compartida

En cada proyecto adicional de Google Cloud que vaya a utilizar la cuenta de servicio, haz lo siguiente:

. En la página _IAM_, seleccione el proyecto de host de VPC compartida en el menú desplegable del proyecto.
. Haga clic en *Agregar director*.
. En el campo Nuevos directores, ingrese la dirección de correo electrónico de su cuenta de servicio.
. En el menú desplegable Seleccionar un rol, elija el rol *Administrador de Google Cloud NetApp Volumes *.
. Haga clic en *Guardar*.
+
Alternativamente, puedes agregar la vinculación de la política IAM usando la CLI de gcloud:

+
[source, cli]
----
gcloud projects add-iam-policy-binding <SHARED_VPC_HOST_PROJECT_ID> --member="serviceAccount:<YOUR_SA_EMAIL>" --role="roles/netapp.admin"
----


Para conocer los pasos detallados, consulte la documentación de Google Cloud:

* link:https://cloud.google.com/iam/docs/creating-managing-service-accounts["Creación y gestión de cuentas de servicio"^]
* link:https://cloud.google.com/iam/docs/roles-permissions/netapp["Roles y permisos de Google Cloud NetApp Volumes"^]
* link:https://cloud.google.com/iam/docs/granting-changing-revoking-access["Conceder, cambiar y revocar el acceso a los recursos"^]




[[troubleshooting]]
== Solución de problemas

Si encuentra un error, es posible que se aplique la política *iam.disableCrossProjectServiceAccountUsage*.  Para solucionar esto, haga lo siguiente:

. En la consola de Google Cloud, vaya a https://console.cloud.google.com/iam-admin/orgpolicies["Página de políticas de la organización"^] .
. Busque la política *Deshabilitar el uso de cuentas de servicio entre proyectos* y deshabilítela.


.¿Que sigue?
link:task-add-roles.html["Asignar roles de Google Cloud NetApp Volumes"].
